trigger: none


pool:
  vmImage: ubuntu-latest
variables:
 rg: 'automationbash'

steps:
- task: AzureCLI@2
  displayName: Create Vnet
  inputs:
    azureSubscription: 'Azure subscription 1(c726bf38-5524-4f36-ae0c-e87f35b14d51)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './vnet.sh'
    arguments: $(rg)

- task: AzureCLI@2
  displayName: Create NSG
  inputs:
    azureSubscription: 'Azure subscription 1(c726bf38-5524-4f36-ae0c-e87f35b14d51)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './nsg.sh'
    arguments: '$(rg)'

- task: AzureCLI@2
  displayName: Assign NSG to Subnet
  inputs:
    azureSubscription: 'Azure subscription 1(c726bf38-5524-4f36-ae0c-e87f35b14d51)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './assigns.sh'
    arguments: '$(rg)'
    

- task: AzureCLI@2
  displayName: Create Vms
  inputs:
    azureSubscription: 'Azure subscription 1(c726bf38-5524-4f36-ae0c-e87f35b14d51)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './vm.sh'
    arguments: '$(rg)'       