on: workflow_dispatch

name: delete

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Checkout
      uses: actions/checkout@v1
      
      
 
    - name: Azure CLI delete
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
                       chmod +x $GITHUB_WORKSPACE/delete.sh
                       $GITHUB_WORKSPACE/delete.sh automation   



    - name: Azure CLI clean
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
                       chmod +x $GITHUB_WORKSPACE/delete.sh
                       $GITHUB_WORKSPACE/delete.sh automation   


