on: [push]

name: AzureCliDepluInfra

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Checkout
      uses: actions/checkout@v1
      
      
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
                       $GITHUB_WORKSPACE/vnet.sh
